# -*- coding: utf-8 -*-
"""text_extraction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bFHF0EYv7CWPQcFO1u2FzGZ7EN_CYYOU
"""

!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

from google.colab import files
uploaded = files.upload()

image_path_in_colab='Screen Shot 2021-11-04 at 10.47.17 PM.png'
extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))
print(extractedInformation)

print(pytesseract.image_to_boxes(Image.open(image_path_in_colab)))
